# Generated by Django 4.1.7 on 2023-04-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=50, unique=b'I01\n')),
            ],
        ),
    ]
