# Generated by Django 4.1.7 on 2023-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_teacher',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=50, unique=b'I01\n')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User_student',
        ),
        migrations.RenameField(
            model_name='user_student',
            old_name='userId',
            new_name='studentId',
        ),
    ]
