# Generated by Django 4.1.7 on 2023-04-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_student_email_user_student_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_teacher',
            name='password',
        ),
    ]
