# Generated by Django 4.1 on 2023-04-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_coursecategory_user_student_interested_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='user_student',
            options={'verbose_name_plural': '4. Student'},
        ),
        migrations.AlterModelOptions(
            name='user_teacher',
            options={'verbose_name_plural': '1. Teachers'},
        ),
    ]
