# Generated by Django 4.1 on 2023-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null='True', upload_to='course_imgs/'),
            preserve_default='True',
        ),
    ]
