# Generated by Django 4.1.7 on 2023-04-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '13. Course Quiz'},
        ),
    ]
