# Generated by Django 4.1.7 on 2023-04-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_coursequiz_options'),
        ('backend', '0009_course_thumbnail'),
    ]

    operations = [
    ]
