# Generated by Django 4.1 on 2023-04-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_course_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_student',
            options={'verbose_name_plural': '5. Student'},
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video', models.FileField(null='True', upload_to='chapter_videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user_teacher')),
            ],
            options={
                'verbose_name_plural': '4. Chapter',
            },
        ),
    ]
