# Generated by Django 4.1.7 on 2023-04-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_quiz_quiz_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='details',
            new_name='detail',
        ),
    ]
