# Generated by Django 4.1.7 on 2023-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_chapter_teacher'),
        ('backend', '0012_rename_details_quiz_detail'),
    ]

    operations = [
    ]
