# Generated by Django 4.1 on 2023-04-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_chapter_course'),
        ('backend', '0014_rename_questions_quizquestions_question'),
    ]

    operations = [
    ]
