# Generated by Django 4.1.7 on 2023-04-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_coursequiz_teacher_alter_chapter_course'),
        ('backend', '0015_merge_20230420_1446'),
    ]

    operations = [
    ]
