# Generated by Django 4.1 on 2023-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_teacher',
            name='bio',
            field=models.TextField(default='null'),
        ),
    ]
