# Generated by Django 4.1.7 on 2023-04-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_merge_20230423_1048'),
        ('backend', '0017_studentcourseenrollment'),
    ]

    operations = [
    ]
