# Generated by Django 4.1.7 on 2023-04-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_merge_20230423_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='attemptQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.quizquestions')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user_student')),
            ],
            options={
                'verbose_name_plural': '14. Attempted Question',
            },
        ),
    ]
