# Generated by Django 4.2 on 2023-04-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_merge_20230423_1742'),
        ('backend', '0021_attemptquiz_quiz'),
    ]

    operations = [
    ]
