# Generated by Django 4.2 on 2023-04-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Rating'},
        ),
    ]
