# Generated by Django 4.1 on 2023-04-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_user_teacher_profile'),
        ('backend', '0024_alter_courserating_options'),
    ]

    operations = [
    ]
