# Generated by Django 4.1 on 2023-05-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_merge_20230425_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null='False', upload_to='chapter_videos/'),
        ),
    ]
