# Generated by Django 4.2 on 2023-05-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_merge_20230425_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFavouriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user_student')),
            ],
            options={
                'verbose_name_plural': '6. Favorite Courses',
            },
        ),
    ]
