# Generated by Django 4.1 on 2023-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_chapter_video'),
        ('backend', '0026_studentfavouritecourse'),
    ]

    operations = [
    ]
