# Generated by Django 4.1.7 on 2023-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(null='False', upload_to='chapter_videos/'),
        ),
    ]
