# Generated by Django 4.1 on 2023-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_chapter_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_student',
            name='security',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_teacher',
            name='security',
            field=models.CharField(default='', max_length=50),
        ),
    ]
