# Generated by Django 4.1.7 on 2023-05-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_uidandtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_student',
            name='security',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uidandtoken',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user_student'),
        ),
        migrations.AlterField(
            model_name='uidandtoken',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user_teacher'),
        ),
    ]
