# Generated by Django 4.1.7 on 2023-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_user_student_security_alter_uidandtoken_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_teacher',
            name='security',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='uidandtoken',
        ),
    ]
